
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/suobset/.cache/JetBrains/RemoteDev/dist/366b89b420705_CLion-252.19874.7/bin/cmake/linux/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.1-microsoft-standard-WSL2 - x86_64
...
